# Generated by Django 3.1.7 on 2021-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='city_per_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='city_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='country_resident_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='date_of_birth_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='full_name_temp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='house_no_per_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='house_no_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='id_type_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='live_video_temp',
            field=models.FileField(blank=True, null=True, upload_to='temp/videos/liv_vid/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='name_init_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='nationality_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='nics_no_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='profile_pic_temp',
            field=models.ImageField(blank=True, null=True, upload_to='temp/images/id_self/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='profile_rating_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='salutation_temp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='street_per_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='street_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='type_of_visa_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
