# Generated by Django 3.1.7 on 2021-04-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_info',
            name='othe_identity_doc',
            field=models.ImageField(blank=True, null=True, upload_to='images/other_doc/'),
        ),
        migrations.AlterField(
            model_name='kyc_info',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pic/'),
        ),
        migrations.AlterField(
            model_name='kyc_info',
            name='vari_doc',
            field=models.ImageField(blank=True, null=True, upload_to='images/vari_doc/'),
        ),
        migrations.AlterField(
            model_name='kyc_info',
            name='visa_copy',
            field=models.ImageField(blank=True, null=True, upload_to='images/visa_copy/'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='othe_identity_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='images/other_doc/'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='profile_pic_temp',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pic/'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='vari_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='images/vari_doc/'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='visa_copy_temp',
            field=models.ImageField(blank=True, null=True, upload_to='images/visa_copy/'),
        ),
    ]
