# Generated by Django 3.1.7 on 2021-06-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_front',
            name='live_video_temp',
            field=models.FileField(blank=True, null=True, upload_to='front/videos/liv_vid/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_front',
            name='othe_identity_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='front/images/other_doc/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_front',
            name='vari_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='front/images/vari_doc/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_front',
            name='visa_copy_temp',
            field=models.ImageField(blank=True, null=True, upload_to='front/images/visa_copy/%Y/%m/%d/'),
        ),
    ]
