# Generated by Django 3.1.7 on 2021-04-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20210421_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='othe_identity_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='profile_pic_temp',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='vari_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='visa_copy_temp',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
