# Generated by Django 3.1.7 on 2021-05-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20210528_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc_front',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation_temp', models.CharField(blank=True, max_length=5, null=True)),
                ('full_name_temp', models.CharField(blank=True, max_length=200, null=True)),
                ('mob_no_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('office_num_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('home_num_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('email_add_temp', models.CharField(blank=True, max_length=100, null=True)),
                ('email_add_verification', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
