# Generated by Django 3.1.7 on 2021-06-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20210604_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc_front',
            name='buisness_trans_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='cash_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='cheque_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='fam_remittance_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='have_acc_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='prof_income_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='rare_trans_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='slip_wir_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='std_order_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
