# Generated by Django 3.1.7 on 2021-06-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_auto_20210605_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc_front',
            name='avg_income_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='in_source_commistion_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='in_source_export_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='in_source_fam_rem_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='in_source_sales_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='occupation_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
