# Generated by Django 3.1.7 on 2021-06-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_kyc_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc_front',
            name='birth_cernum_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='blue_flag_temp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='check_city',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='check_home',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='check_name',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='check_street',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='city_per_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='city_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='country_resident_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='date_of_birth_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='driv_exp_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='driv_lic_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='foreign_addre_temp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='green_flag_temp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='house_no_per_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='house_no_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='id_type_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='live_video_temp',
            field=models.FileField(blank=True, null=True, upload_to='temp/videos/liv_vid/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='name_init_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='nationality_other_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='nationality_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='nics_no_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='oafsc_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='othe_identity_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='temp/images/other_doc/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='other_exp_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='other_types_temp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='pass_exp_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='pass_no_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='pep_person_temp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='post_id_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='postal_code_per_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='postal_code_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='profile_pic_temp',
            field=models.ImageField(blank=True, null=True, upload_to='temp/images/id_self/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='profile_rating_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='red_flag_temp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='resident_sri_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='state_address_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='street_per_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='street_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='submited_form',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='type_of_visa_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='us_city_temp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='vari_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='temp/images/vari_doc/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='vari_doc_type_temp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='visa_copy_temp',
            field=models.ImageField(blank=True, null=True, upload_to='temp/images/visa_copy/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='visa_exp_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_front',
            name='mob_no_temp',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='kyc_front',
            table='Kyc_front',
        ),
    ]
