# Generated by Django 3.1.7 on 2021-04-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_auto_20210423_1717'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kyc_info',
            table='Kyc_Info',
        ),
    ]
