# Generated by Django 3.1.7 on 2021-06-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_auto_20210604_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_front',
            name='check_city',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_front',
            name='check_home',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_front',
            name='check_name',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_front',
            name='check_street',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_front',
            name='submited_form',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
