# Generated by Django 3.1.7 on 2021-06-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_auto_20210605_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkyc_info',
            name='post_id_exp_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kyc_info',
            name='post_id_exp_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
