# Generated by Django 3.1.7 on 2021-04-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_auto_20210423_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_info',
            name='date_of_birth',
            field=models.CharField(max_length=20),
        ),
    ]
