# Generated by Django 3.1.7 on 2021-06-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_auto_20210604_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc_front',
            name='post_id_exp_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
