# Generated by Django 3.1.7 on 2021-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_kyc_front_post_id_exp_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc_front',
            name='account_type_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc_front',
            name='occu_state_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
