# Generated by Django 3.1.7 on 2021-06-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_auto_20210605_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc_front',
            name='blue_flag_temp',
        ),
        migrations.RemoveField(
            model_name='kyc_front',
            name='check_city',
        ),
        migrations.RemoveField(
            model_name='kyc_front',
            name='check_home',
        ),
        migrations.RemoveField(
            model_name='kyc_front',
            name='check_name',
        ),
        migrations.RemoveField(
            model_name='kyc_front',
            name='check_street',
        ),
        migrations.RemoveField(
            model_name='kyc_front',
            name='green_flag_temp',
        ),
        migrations.RemoveField(
            model_name='kyc_front',
            name='profile_rating_temp',
        ),
        migrations.RemoveField(
            model_name='kyc_front',
            name='red_flag_temp',
        ),
        migrations.RemoveField(
            model_name='kyc_front',
            name='submited_form',
        ),
    ]
