# Generated by Django 3.1.7 on 2021-04-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_auto_20210424_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_info',
            name='profile_pic_temp',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='profile_pic_temp',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name=''),
        ),
    ]
