# Generated by Django 3.1.7 on 2021-06-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0008_auto_20210606_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkyc_info',
            name='email_varified_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kyc_info',
            name='email_varified_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
