# Generated by Django 3.1.7 on 2021-06-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0009_auto_20210606_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc_infotemp',
            name='email_varified_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
