# Generated by Django 2.2.10 on 2021-04-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0009_auto_20210427_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_info',
            name='profile_pic_temp',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='profile_pic_temp',
            field=models.ImageField(upload_to='images'),
        ),
    ]
