# Generated by Django 2.2.10 on 2021-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0010_auto_20210429_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_info',
            name='profile_pic_temp',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='profile_pic_temp',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
