# Generated by Django 3.1.7 on 2021-07-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0011_auto_20210607_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_qualifi', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_details', models.CharField(blank=True, max_length=50, null=True)),
                ('spent_hours_video', models.IntegerField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, max_length=50, null=True)),
                ('relations_name', models.CharField(blank=True, max_length=255, null=True)),
                ('relations_address', models.CharField(blank=True, max_length=255, null=True)),
                ('rel_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('rel_job_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rel_job_status', models.CharField(blank=True, max_length=50, null=True)),
                ('friend_name', models.CharField(blank=True, max_length=255, null=True)),
                ('friend_address', models.CharField(blank=True, max_length=255, null=True)),
                ('friend_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('friend_job_type', models.CharField(blank=True, max_length=50, null=True)),
                ('friend_job_status', models.CharField(blank=True, max_length=50, null=True)),
                ('volun_service', models.CharField(blank=True, max_length=20, null=True)),
                ('ser_heart', models.CharField(blank=True, max_length=10, null=True)),
                ('ser_cancer', models.CharField(blank=True, max_length=10, null=True)),
                ('ser_kidney', models.CharField(blank=True, max_length=10, null=True)),
                ('ser_none', models.CharField(blank=True, max_length=10, null=True)),
                ('ser_other', models.CharField(blank=True, max_length=10, null=True)),
                ('dis_diabetics', models.CharField(blank=True, max_length=10, null=True)),
                ('dis_cholestrol', models.CharField(blank=True, max_length=10, null=True)),
                ('dis_blood_presure', models.CharField(blank=True, max_length=10, null=True)),
                ('dis_none', models.CharField(blank=True, max_length=10, null=True)),
                ('dis_other', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
