# Generated by Django 3.1.7 on 2021-07-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0012_social_core'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social_core',
            old_name='job_type',
            new_name='job_status',
        ),
        migrations.RemoveField(
            model_name='social_core',
            name='friend_relationship',
        ),
    ]
