# Generated by Django 2.2.10 on 2021-04-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0012_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='profile_pic_temp',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
