# Generated by Django 2.2.10 on 2021-04-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0014_auto_20210429_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc_info',
            name='live_video_temp',
        ),
        migrations.RemoveField(
            model_name='kyc_infotemp',
            name='live_video_temp',
        ),
        migrations.AlterField(
            model_name='kyc_info',
            name='profile_pic_temp',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name=''),
        ),
    ]
