# Generated by Django 2.2.10 on 2021-04-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0015_auto_20210429_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc_info',
            name='live_video_temp',
            field=models.FileField(null=True, upload_to='videos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='kyc_infotemp',
            name='live_video_temp',
            field=models.FileField(null=True, upload_to='videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_info',
            name='profile_pic_temp',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
