# Generated by Django 2.2.10 on 2021-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0016_auto_20210429_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_info',
            name='live_video_temp',
            field=models.FileField(null=True, upload_to='per/videos/liv_vid/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_info',
            name='othe_identity_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='per/images/other_doc/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_info',
            name='profile_pic_temp',
            field=models.FileField(blank=True, null=True, upload_to='per/images/id_self/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_info',
            name='vari_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='per/images/vari_doc/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_info',
            name='visa_copy_temp',
            field=models.ImageField(blank=True, null=True, upload_to='per/images/visa_copy/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='live_video_temp',
            field=models.FileField(null=True, upload_to='temp/videos/liv_vid/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='othe_identity_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='per/images/other_doc/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='profile_pic_temp',
            field=models.ImageField(null=True, upload_to='temp/images/id_self/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='vari_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='per/images/vari_doc/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='visa_copy_temp',
            field=models.ImageField(blank=True, null=True, upload_to='temp/images/visa_copy/%Y/%m/%d/'),
        ),
    ]
