# Generated by Django 2.2.10 on 2021-04-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0017_auto_20210429_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='othe_identity_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='temp/images/other_doc/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='vari_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='temp/images/vari_doc/%Y/%m/%d/'),
        ),
    ]
