# Generated by Django 2.2.10 on 2021-05-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0018_auto_20210429_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc_info',
            name='email_add_verification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc_infotemp',
            name='email_add_verification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
