# Generated by Django 2.2.10 on 2021-05-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0019_auto_20210502_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc_Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation_temp', models.CharField(max_length=5)),
                ('full_name_temp', models.CharField(max_length=200)),
                ('name_init_temp', models.CharField(max_length=100)),
                ('profile_pic_temp', models.ImageField(null=True, upload_to='temp/images/id_self/%Y/%m/%d/')),
                ('live_video_temp', models.FileField(null=True, upload_to='temp/videos/liv_vid/%Y/%m/%d/')),
                ('id_type_temp', models.CharField(max_length=50)),
                ('nics_no_temp', models.CharField(max_length=50)),
                ('date_of_birth_temp', models.CharField(max_length=20)),
                ('driv_lic_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('driv_exp_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('pass_no_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('pass_exp_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_cernum_temp', models.CharField(blank=True, max_length=10, null=True)),
                ('post_id_temp', models.CharField(blank=True, max_length=10, null=True)),
                ('oafsc_temp', models.CharField(blank=True, max_length=10, null=True)),
                ('visa_copy_temp', models.ImageField(blank=True, null=True, upload_to='temp/images/visa_copy/%Y/%m/%d/')),
                ('othe_identity_doc_temp', models.ImageField(blank=True, null=True, upload_to='temp/images/other_doc/%Y/%m/%d/')),
                ('nationality_temp', models.CharField(max_length=50)),
                ('nationality_other_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('type_of_visa_temp', models.CharField(blank=True, max_length=20)),
                ('visa_exp_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('other_types_temp', models.CharField(blank=True, max_length=20)),
                ('other_exp_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('foreign_addre_temp', models.CharField(blank=True, max_length=200, null=True)),
                ('vari_doc_type_temp', models.CharField(blank=True, max_length=200, null=True)),
                ('vari_doc_temp', models.ImageField(blank=True, null=True, upload_to='temp/images/vari_doc/%Y/%m/%d/')),
                ('pep_person_temp', models.CharField(blank=True, max_length=200, null=True)),
                ('us_city_temp', models.CharField(blank=True, max_length=200, null=True)),
                ('resident_sri_temp', models.CharField(blank=True, max_length=10, null=True)),
                ('country_resident_temp', models.CharField(blank=True, max_length=50)),
                ('house_no_temp', models.CharField(max_length=20)),
                ('street_temp', models.CharField(max_length=20)),
                ('city_temp', models.CharField(max_length=20)),
                ('postal_code_temp', models.CharField(blank=True, max_length=10, null=True)),
                ('state_address_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('house_no_per_temp', models.CharField(max_length=20)),
                ('street_per_temp', models.CharField(max_length=20)),
                ('city_per_temp', models.CharField(max_length=20)),
                ('postal_code_per_temp', models.CharField(blank=True, max_length=10, null=True)),
                ('mob_no_temp', models.CharField(max_length=20)),
                ('office_num_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('home_num_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('email_add_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('email_add_verification', models.CharField(blank=True, max_length=50, null=True)),
                ('red_flag_temp', models.CharField(blank=True, max_length=5, null=True)),
                ('blue_flagadd_temp', models.CharField(blank=True, max_length=5, null=True)),
                ('blue_flag_temp', models.CharField(blank=True, max_length=5, null=True)),
                ('date_now_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('staff_member_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('file_note_temp', models.CharField(blank=True, max_length=200, null=True)),
                ('rejected_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('reason_for_rej_temp', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Kyc_Reject',
            },
        ),
    ]
