# Generated by Django 2.2.10 on 2021-05-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0020_kyc_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_reject',
            name='date_now_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
