# Generated by Django 2.2.10 on 2021-05-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0021_auto_20210503_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc_reject',
            name='file_attachment_temp',
            field=models.FileField(null=True, upload_to='rej/videos/liv_vid/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_reject',
            name='file_note_temp',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_reject',
            name='live_video_temp',
            field=models.FileField(null=True, upload_to='rej/videos/liv_vid/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_reject',
            name='othe_identity_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='rej/images/other_doc/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_reject',
            name='profile_pic_temp',
            field=models.ImageField(null=True, upload_to='rej/images/id_self/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_reject',
            name='vari_doc_temp',
            field=models.ImageField(blank=True, null=True, upload_to='rej/images/vari_doc/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kyc_reject',
            name='visa_copy_temp',
            field=models.ImageField(blank=True, null=True, upload_to='rej/images/visa_copy/%Y/%m/%d/'),
        ),
    ]
