# Generated by Django 2.2.10 on 2021-05-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0022_auto_20210504_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc_info',
            old_name='blue_flagadd_temp',
            new_name='green_flag_temp',
        ),
        migrations.RenameField(
            model_name='kyc_infotemp',
            old_name='blue_flagadd_temp',
            new_name='green_flag_temp',
        ),
        migrations.RenameField(
            model_name='kyc_reject',
            old_name='blue_flagadd_temp',
            new_name='green_flag_temp',
        ),
    ]
