# Generated by Django 3.1.7 on 2021-05-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0026_remove_historicalkyc_info_green_flag_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkyc_info',
            name='profile_rating_temp',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc_info',
            name='profile_rating_temp',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc_infotemp',
            name='profile_rating_temp',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc_reject',
            name='profile_rating_temp',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
